services:
  ocelot.api:
    image: ${DOCKER_REGISTRY-}ocelotapi
    build:
      context: .
      dockerfile: src/APIGateway/Ocelot.API/Dockerfile

  arbitrageapi:
    image: ${DOCKER_REGISTRY-}arbitrageapi
    build:
      context: .
      dockerfile: src/ArbitrageService/ArbitrageAPI/Dockerfile


  pricedata.api:
    image: ${DOCKER_REGISTRY-}pricedataapi
    build:
      context: .
      dockerfile: src/PriceDataService/PriceData.API/Dockerfile

