global using Arbitrage.Application.Interfaces;
global using Arbitrage.Application.Services;
global using Arbitrage.Infrastructure.Data;
global using Arbitrage.Infrastructure.Repositories;
global using Carter;
global using Microsoft.EntityFrameworkCore;
global using RabbitMQ.Interfaces;
global using RabbitMQ.Services;
global using Serilog;